version: "3"

env:
  AMBULANCE_API_ENVIRONMENT: Development
  AMBULANCE_API_PORT: "8083"
  AMBULANCE_API_MONGODB_PORT: "27018"
  AMBULANCE_API_MONGODB_USERNAME: root
  AMBULANCE_API_MONGODB_PASSWORD: secret

tasks:
  default:
    cmds:
      - task: start

  start:
    cmds:
      - docker compose --file ./deployments/docker-compose/compose.yaml up --detach
      - defer: docker compose --file ./deployments/docker-compose/compose.yaml down
      - go run ./cmd/ambulance-api-service

  mongo:
    cmds:
      - docker compose --file ./deployments/docker-compose/compose.yaml up

  test:
    cmds:
      - go test -v ./...

  openapi:
    cmds:
      - docker run --rm -ti -v {{.ROOT_DIR}}:/local openapitools/openapi-generator-cli generate -c /local/scripts/generator-cfg.yaml

  docker:
    cmds:
      - docker build -t fiitkar/davgus-ambulance-wl-webapi:local-build -f {{.ROOT_DIR}}/build/docker/Dockerfile .
