version: "3"

env:
  AMBULANCE_API_ENVIRONMENT: Development
  AMBULANCE_API_PORT: "8080"

tasks:
  default:
    cmds:
      - task: start

  start:
    cmds:
      - go run ./cmd/ambulance-api-service

  openapi:
    cmds:
      - docker run --rm -ti -v {{.ROOT_DIR}}:/local openapitools/openapi-generator-cli generate -c /local/scripts/generator-cfg.yaml
