/*
 * davgus ambulance API
 *
 * Patient, department and placement management for davgus-ambulance
 *
 * API version: 1.0.0
 * Contact: xdavydau@stuba.sk, xgusiev@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type DepartmentsAPI interface {


    // GetDepartment Get /api/departments/:departmentId
    // Get department by id 
     GetDepartment(c *gin.Context)

    // GetDepartments Get /api/departments
    // Get all departments 
     GetDepartments(c *gin.Context)

    // UpdateDepartment Put /api/departments/:departmentId
    // Update department 
     UpdateDepartment(c *gin.Context)

}