/*
 * davgus ambulance API
 *
 * Patient, department and placement management for davgus-ambulance
 *
 * API version: 1.0.0
 * Contact: xdavydau@stuba.sk, xgusiev@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type PatientsAPI interface {


    // CreatePatient Post /api/patients
    // Create patient 
     CreatePatient(c *gin.Context)

    // DeletePatient Delete /api/patients/:patientId
    // Archive patient 
     DeletePatient(c *gin.Context)

    // GetPatient Get /api/patients/:patientId
    // Get patient by id 
     GetPatient(c *gin.Context)

    // GetPatients Get /api/patients
    // Get all active patients 
     GetPatients(c *gin.Context)

    // UpdatePatient Put /api/patients/:patientId
    // Update patient 
     UpdatePatient(c *gin.Context)

}