/*
 * davgus ambulance API
 *
 * Patient, department and placement management for davgus-ambulance
 *
 * API version: 1.0.0
 * Contact: xdavydau@stuba.sk, xgusiev@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type PlacementsAPI interface {


    // CreatePlacement Post /api/placements
    // Create placement 
     CreatePlacement(c *gin.Context)

    // DeletePlacement Delete /api/placements/:placementId
    // Delete placement 
     DeletePlacement(c *gin.Context)

    // GetPlacement Get /api/placements/:placementId
    // Get placement by id 
     GetPlacement(c *gin.Context)

    // GetPlacementForPatient Get /api/patients/:patientId/placement
    // Get placement for patient 
     GetPlacementForPatient(c *gin.Context)

    // GetPlacements Get /api/placements
    // Get all placements 
     GetPlacements(c *gin.Context)

    // UpdatePlacement Put /api/placements/:placementId
    // Update placement 
     UpdatePlacement(c *gin.Context)

}