/*
 * davgus ambulance API
 *
 * Patient, department and placement management for davgus-ambulance
 *
 * API version: 1.0.0
 * Contact: xdavydau@stuba.sk, xgusiev@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

type PatientCreateRequest struct {

	Name string `json:"name"`

	BirthDate string `json:"birthDate"`

	InsuranceId string `json:"insuranceId"`

	InsuranceCompany string `json:"insuranceCompany"`

	Phone string `json:"phone"`

	Email string `json:"email"`

	Archived bool `json:"archived,omitempty"`
}
