/*
 * davgus ambulance API
 *
 * Patient, department and placement management for davgus-ambulance
 *
 * API version: 1.0.0
 * Contact: xdavydau@stuba.sk, xgusiev@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

type Department struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Rooms []Room `json:"rooms"`
}
