/*
 * davgus ambulance API
 *
 * Patient, department and placement management for davgus-ambulance
 *
 * API version: 1.0.0
 * Contact: xdavydau@stuba.sk, xgusiev@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

type Room struct {

	Id string `json:"id"`

	Number string `json:"number"`

	Capacity int32 `json:"capacity"`

	Status string `json:"status"`
}
