/*
 * davgus ambulance API
 *
 * Patient, department and placement management for davgus-ambulance
 *
 * API version: 1.0.0
 * Contact: xdavydau@stuba.sk, xgusiev@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

type Placement struct {

	Id string `json:"id"`

	PatientId string `json:"patientId"`

	PatientName string `json:"patientName"`

	DepartmentId string `json:"departmentId"`

	DepartmentName string `json:"departmentName"`

	RoomId string `json:"roomId"`

	RoomNumber string `json:"roomNumber"`

	AdmissionDate string `json:"admissionDate"`

	Notes string `json:"notes"`
}
