/*
 * davgus ambulance API
 *
 * Patient, department and placement management for davgus-ambulance
 *
 * API version: 1.0.0
 * Contact: xdavydau@stuba.sk, xgusiev@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the DepartmentsAPI part of the API
	DepartmentsAPI DepartmentsAPI
	// Routes for the PatientsAPI part of the API
	PatientsAPI PatientsAPI
	// Routes for the PlacementsAPI part of the API
	PlacementsAPI PlacementsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateDepartment",
			http.MethodPost,
			"/api/departments",
			handleFunctions.DepartmentsAPI.CreateDepartment,
		},
		{
			"DeleteDepartment",
			http.MethodDelete,
			"/api/departments/:departmentId",
			handleFunctions.DepartmentsAPI.DeleteDepartment,
		},
		{
			"GetDepartment",
			http.MethodGet,
			"/api/departments/:departmentId",
			handleFunctions.DepartmentsAPI.GetDepartment,
		},
		{
			"GetDepartments",
			http.MethodGet,
			"/api/departments",
			handleFunctions.DepartmentsAPI.GetDepartments,
		},
		{
			"UpdateDepartment",
			http.MethodPut,
			"/api/departments/:departmentId",
			handleFunctions.DepartmentsAPI.UpdateDepartment,
		},
		{
			"CreatePatient",
			http.MethodPost,
			"/api/patients",
			handleFunctions.PatientsAPI.CreatePatient,
		},
		{
			"DeletePatient",
			http.MethodDelete,
			"/api/patients/:patientId",
			handleFunctions.PatientsAPI.DeletePatient,
		},
		{
			"GetPatient",
			http.MethodGet,
			"/api/patients/:patientId",
			handleFunctions.PatientsAPI.GetPatient,
		},
		{
			"GetPatients",
			http.MethodGet,
			"/api/patients",
			handleFunctions.PatientsAPI.GetPatients,
		},
		{
			"UpdatePatient",
			http.MethodPut,
			"/api/patients/:patientId",
			handleFunctions.PatientsAPI.UpdatePatient,
		},
		{
			"CreatePlacement",
			http.MethodPost,
			"/api/placements",
			handleFunctions.PlacementsAPI.CreatePlacement,
		},
		{
			"DeletePlacement",
			http.MethodDelete,
			"/api/placements/:placementId",
			handleFunctions.PlacementsAPI.DeletePlacement,
		},
		{
			"GetPlacement",
			http.MethodGet,
			"/api/placements/:placementId",
			handleFunctions.PlacementsAPI.GetPlacement,
		},
		{
			"GetPlacementForPatient",
			http.MethodGet,
			"/api/patients/:patientId/placement",
			handleFunctions.PlacementsAPI.GetPlacementForPatient,
		},
		{
			"GetPlacements",
			http.MethodGet,
			"/api/placements",
			handleFunctions.PlacementsAPI.GetPlacements,
		},
		{
			"UpdatePlacement",
			http.MethodPut,
			"/api/placements/:placementId",
			handleFunctions.PlacementsAPI.UpdatePlacement,
		},
	}
}
